### ISSUE TITLE
Is this DNSProxyProvider can use in iOS Network Extension.

### ISSUE THREAD

**Issue by MaheshPatil86** [objective-see/DNSMonitor#1]
Hi,

Thanks for this source code.

We are working on app where we want to use NEDNSProxyProvider network extension for our iOS and MacOS app that filter out DNS ProxyQueries with TCP and UDP flow.

So I have following queries regarding this source code.

- Can we use these DNSProxyProvider.h & .m in MacOS system extension as well as iOS Network Extension.
- Your current app include terminal to run the app, Can we connect this system extension with OSX UI, instead of Terminal.

**Comment by objective-see** [comment]
I imagine that since NEDNSProxyProvider is also supported on iOS (11+), then yes - in theory, it should also work on iOS (though I have not tested this). 

Yes, it should be fairly straightforward to create a UI for this. I'd recommend using XPC to send DNS events from system extension to a helper app (with a UI), running in/on the desktop user session.
